[TITLE]
SubViewer1
[AUTHOR]
[SOURCE]
[PRG]
[FILEPATH]
[DELAY]
0
[CD TRACK]
0
[BEGIN]
******** START SCRIPT ********
[00:00:16]
Mr Bond?
[00:00:18]

[00:00:20]
Yes?
[00:00:22]

[00:00:22]
I'm Lieutenant Mathis|of the Special Police.
[00:00:25]

[00:00:29]
These are my credentials.
[00:00:31]

[00:00:32]
They appear to be in order.
[00:00:34]

[00:00:34]
Come with me.
[00:00:36]

[end]
******** END SCRIPT ********
