[INFORMATION]
[TITLE]SubViewer2
[AUTHOR]
[SOURCE]
[PRG]
[FILEPATH]
[DELAY]0
[CD TRACK]0
[COMMENT]
[END INFORMATION]
[SUBTITLE]
[COLF]&H000000,[STYLE]bd,[SIZE]25,[FONT]Arial
00:00:16.85,00:00:18.89
Mr Bond?

00:00:20.73,00:00:22.15
Yes?

00:00:22.23,00:00:25.19
I'm Lieutenant Mathis[br]of the Special Police.

00:00:29.20,00:00:31.95
These are my credentials.

00:00:32.03,00:00:34.08
They appear to be in order.

00:00:34.20,00:00:36.41
Come with me.
