name: Create Tag Release

on:
  push:
    tags:
      - v*

permissions:
  contents: write

jobs:
  release:
    name: Create Tag Release
    runs-on: ubuntu-latest
    # See https://cli.github.com/manual/gh
    steps:
      - name: Create Release
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REF_NAME: ${{ github.ref_name }}
        run: |
          gh release create "${REF_NAME}" \
            --title="${REF_NAME}" \
            --repo="${GITHUB_REPOSITORY}" \
            --generate-notes
      - name: Checkout Code
        id: checkout_code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Create Assets
        id: create_assets
        env:
          REF_NAME: ${{ github.ref_name }}
        run: |
          git archive ${REF_NAME} \
            --format zip \
            --prefix service.subtitles.universalsubs/ \
            --output service.subtitles.universalsubs-${REF_NAME}.zip \
            ":!.github" \
            ":!resources/examples"
      - name: Upload Assets
        id: upload_assets
        env:
          GITHUB_TOKEN: ${{ github.token }}
          REF_NAME: ${{ github.ref_name }}
        run: |
          gh release upload "${REF_NAME}" \
            service.subtitles.universalsubs-${REF_NAME}.zip
